### ISSUE TITLE
Can't find documentation on resizing images

### ISSUE THREAD

**Issue by pjotrek-b** [picocms/picocms.github.io#14]
Hi :)
I didn't know whether this or the "pico" project itself are the right place to ask this. Sorry if I'm wrong here.

Searching the website documentation of Pico, I couldn't find any information about how to resize images. Is this possible and is it documented anywhere?

Thank you very much in advance.

**Comment by PhrozenByte** [comment]
You can find Pico's main repo here: https://github.com/picocms/Pico

Please open a new Issue there. This allows others to find your question and the corresponding answer/solution later. Thanks! 👍

**Comment by pjotrek-b** [comment]
Roger that. Will post it there.
Thanks! :smile:
