### ISSUE TITLE
Tested version of Pico for each plugin and theme

### ISSUE THREAD

**Issue by anasram** [picocms/picocms.github.io#22]
I think each official plugin/theme should state explicitly the tested/compatible version of Pico for it.

e.g.:

> Pagination
> By: rewdy
> License: The MIT License
> **Tested on**: Pico 2.0

**Comment by PhrozenByte** [comment]
Promoted plugins (i.e. plugins listed on our website) must support the latest major/minor version of Pico (i.e. Pico 2.0). If a plugin doesn't support the current major/minor release, it must be removed from our website (but can still be listed in our Wiki, including a notice that it is supported by e.g. Pico 1.0 only). So I would say that this information would be redundant, or do I miss something? If a plugin doesn't work with Pico 2.0, please don't hesitate to open a new Issue here on GitHub :+1:  Feedback is appreciated!
