### ISSUE TITLE
Twig URLs broken

### ISSUE THREAD

**Issue by PhrozenByte** [picocms/picocms.github.io#62]
Reported via IRC: https://twig.sensiolabs.org/ is offline, Twig's new home is https://twig.symfony.com/

**Comment by mayamcdougall** [comment]
I'm pretty sure I've updated this in a couple places before, but I guess I should have done a search of the entire repo(s).

I'll take a look in a bit and see where the holdovers are. 🤔

**Comment by mayamcdougall** [comment]
Should be fixed everywhere except in the phpDocs now.

https://github.com/picocms/picocms.github.io/commit/7dd1d33cb02681298e36edd01c6be685ecf52b56

https://github.com/picocms/Pico/commit/09aa82578710d82dd7dc482febe32991be0ea307

**Comment by PhrozenByte** [comment]
Thanks Maya! :heart:
